# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataProcess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447, 483)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.mubansheet_textEdit = QtWidgets.QTextEdit(Form)
        self.mubansheet_textEdit.setGeometry(QtCore.QRect(30, 50, 381, 31))
        self.mubansheet_textEdit.setObjectName("mubansheet_textEdit")
        self.mubansheet_label = QtWidgets.QLabel(Form)
        self.mubansheet_label.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.mubansheet_label.setObjectName("mubansheet_label")
        self.mubanwenjian_textEdit = QtWidgets.QTextEdit(Form)
        self.mubanwenjian_textEdit.setGeometry(QtCore.QRect(30, 130, 381, 31))
        self.mubanwenjian_textEdit.setObjectName("mubanwenjian_textEdit")
        self.muban_label = QtWidgets.QLabel(Form)
        self.muban_label.setGeometry(QtCore.QRect(30, 100, 371, 21))
        self.muban_label.setObjectName("muban_label")
        self.zonshuju_textEdit = QtWidgets.QTextEdit(Form)
        self.zonshuju_textEdit.setGeometry(QtCore.QRect(30, 230, 381, 31))
        self.zonshuju_textEdit.setObjectName("zonshuju_textEdit")
        self.zonshuju_label = QtWidgets.QLabel(Form)
        self.zonshuju_label.setGeometry(QtCore.QRect(30, 200, 371, 21))
        self.zonshuju_label.setObjectName("zonshuju_label")
        self.zonshujusheet_textEdit = QtWidgets.QTextEdit(Form)
        self.zonshujusheet_textEdit.setGeometry(QtCore.QRect(30, 320, 381, 31))
        self.zonshujusheet_textEdit.setObjectName("zonshujusheet_textEdit")
        self.zonshujusheet_label = QtWidgets.QLabel(Form)
        self.zonshujusheet_label.setGeometry(QtCore.QRect(30, 290, 71, 21))
        self.zonshujusheet_label.setObjectName("zonshujusheet_label")
        self.confirm_Button = QtWidgets.QPushButton(Form)
        self.confirm_Button.setGeometry(QtCore.QRect(330, 380, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.confirm_Button.setFont(font)
        self.confirm_Button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.confirm_Button.setObjectName("confirm_Button")
        self.mubandakai_pushButton = QtWidgets.QPushButton(Form)
        self.mubandakai_pushButton.setGeometry(QtCore.QRect(330, 170, 75, 23))
        self.mubandakai_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.mubandakai_pushButton.setObjectName("mubandakai_pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 270, 75, 23))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 420, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "dataProcess"))
        self.mubansheet_label.setText(_translate("Form", "模板sheet"))
        self.muban_label.setText(_translate("Form", "模板文件路径,支持拖文件/手动选择文件"))
        self.zonshuju_label.setText(_translate("Form", "总数据文件路径，支持拖文件/手动选择文件"))
        self.zonshujusheet_label.setText(_translate("Form", "总数据sheet"))
        self.confirm_Button.setText(_translate("Form", "开始"))
        self.mubandakai_pushButton.setText(_translate("Form", "open file"))
        self.pushButton_2.setText(_translate("Form", "open file"))
        self.label.setText(_translate("Form", ""))
